import { NgModule } from '@angular/core';
import {
  DxBoxModule,
  DxButtonModule,
  DxChartModule,
  DxCheckBoxModule,
  DxDataGridModule,
  DxFormModule,
  DxNavBarModule,
  DxNumberBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxTemplateModule,
  DxFileUploaderModule,
  DxTreeViewModule,
  DxPopupModule, 
  DxPopoverModule,
  DxScrollViewModule,
  DxToolbarModule,
  DxPolarChartModule,
  DxValidatorModule
} from 'devextreme-angular';

@NgModule({
  imports: [
    DxButtonModule,
    DxChartModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxNumberBoxModule,
    DxFormModule,
    DxBoxModule,
    DxDataGridModule,
    DxNavBarModule,
    DxTextBoxModule,
    DxTemplateModule,
    DxFileUploaderModule,
    DxTreeViewModule,
    DxPopupModule, 
    DxPopoverModule,
    DxSelectBoxModule,
    DxFormModule,
    DxScrollViewModule,
    DxToolbarModule,
    DxPolarChartModule,
    DxValidatorModule
  ],
  exports: [
    DxButtonModule,
    DxChartModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxNumberBoxModule,
    DxFormModule,
    DxBoxModule,
    DxDataGridModule,
    DxNavBarModule,
    DxTextBoxModule,
    DxTemplateModule,
    DxFileUploaderModule,
    DxTreeViewModule,
    DxPopupModule, 
    DxPopoverModule,
    DxSelectBoxModule,
    DxFormModule,
    DxScrollViewModule,
    DxToolbarModule,
    DxPolarChartModule,
    DxValidatorModule
  ]
})
export class DevExtremeModule { }
