INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (1, 'AF', 'AFG', 'Afghanistan', 'Afganistán', 'Afghanistan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (2, 'AL', 'ALB', 'Albania', 'Albania', 'Albanie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (3, 'DE', 'DEU', 'Germany', 'Alemania', 'Allemagne')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (4, 'AD', 'AND', 'Andorra', 'Andorra', 'Andorra')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (5, 'AO', 'AGO', 'Angola', 'Angola', 'Angola')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (6, 'AI', 'AIA', 'Anguilla', 'Anguila', 'Anguilla')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (7, 'AQ', 'ATA', 'Antarctica', 'Antártida', 'L''Antarctique')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (8, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua y Barbuda', 'Antigua et Barbuda')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (9, 'SA', 'SAU', 'Saudi Arabia', 'Arabia Saudita', 'Arabie Saoudite')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (10, 'DZ', 'DZA', 'Algeria', 'Argelia', 'Algérie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (11, 'AR', 'ARG', 'Argentina', 'Argentina', 'Argentine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (12, 'AM', 'ARM', 'Armenia', 'Armenia', 'L''Arménie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (13, 'AW', 'ABW', 'Aruba', 'Aruba', 'Aruba')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (14, 'AU', 'AUS', 'Australia', 'Australia', 'Australie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (15, 'AT', 'AUT', 'Austria', 'Austria', 'Autriche')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (16, 'AZ', 'AZE', 'Azerbaijan', 'Azerbaiyán', 'L''Azerbaïdjan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (17, 'BE', 'BEL', 'Belgium', 'Bélgica', 'Belgique')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (18, 'BS', 'BHS', 'Bahamas', 'Bahamas', 'Bahamas')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (19, 'BH', 'BHR', 'Bahrain', 'Bahrein', 'Bahreïn')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (20, 'BD', 'BGD', 'Bangladesh', 'Bangladesh', 'Bangladesh')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (21, 'BB', 'BRB', 'Barbados', 'Barbados', 'Barbade')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (22, 'BZ', 'BLZ', 'Belize', 'Belice', 'Belize')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (23, 'BJ', 'BEN', 'Benin', 'Benín', 'Bénin')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (24, 'BT', 'BTN', 'Bhutan', 'Bhután', 'Le Bhoutan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (25, 'BY', 'BLR', 'Belarus', 'Bielorrusia', 'Biélorussie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (26, 'MM', 'MMR', 'Myanmar', 'Birmania', 'Myanmar')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (27, 'BO', 'BOL', 'Bolivia', 'Bolivia', 'Bolivie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (28, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'Bosnie-Herzégovine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (29, 'BW', 'BWA', 'Botswana', 'Botsuana', 'Botswana')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (30, 'BR', 'BRA', 'Brazil', 'Brasil', 'Brésil')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (31, 'BN', 'BRN', 'Brunei', 'Brunéi', 'Brunei')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (32, 'BG', 'BGR', 'Bulgaria', 'Bulgaria', 'Bulgarie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (33, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (34, 'BI', 'BDI', 'Burundi', 'Burundi', 'Burundi')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (35, 'CV', 'CPV', 'Cape Verde', 'Cabo Verde', 'Cap-Vert')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (36, 'KH', 'KHM', 'Cambodia', 'Camboya', 'Cambodge')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (37, 'CM', 'CMR', 'Cameroon', 'Camerún', 'Cameroun')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (38, 'CA', 'CAN', 'Canada', 'Canadá', 'Canada')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (39, 'TD', 'TCD', 'Chad', 'Chad', 'Tchad')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (40, 'CL', 'CHL', 'Chile', 'Chile', 'Chili')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (41, 'CN', 'CHN', 'China', 'China', 'Chine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (42, 'CY', 'CYP', 'Cyprus', 'Chipre', 'Chypre')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (43, 'VA', 'VAT', 'Vatican City State', 'Ciudad del Vaticano', 'Cité du Vatican')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (44, 'CO', 'COL', 'Colombia', 'Colombia', 'Colombie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (45, 'KM', 'COM', 'Comoros', 'Comoras', 'Comores')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (46, 'CG', 'COG', 'Republic of the Congo', 'República del Congo', 'République du Congo')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (47, 'CD', 'COD', 'Democratic Republic of the Congo', 'República Democrática del Congo', 'République démocratique du Congo')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (48, 'KP', 'PRK', 'North Korea', 'Corea del Norte', 'Corée du Nord')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (49, 'KR', 'KOR', 'South Korea', 'Corea del Sur', 'Corée du Sud')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (50, 'CI', 'CIV', 'Ivory Coast', 'Costa de Marfil', 'Côte-d''Ivoire')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (51, 'CR', 'CRI', 'Costa Rica', 'Costa Rica', 'Costa Rica')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (52, 'HR', 'HRV', 'Croatia', 'Croacia', 'Croatie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (53, 'CU', 'CUB', 'Cuba', 'Cuba', 'Cuba')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (54, 'CW', 'CWU', 'Curaçao', 'Curazao', 'Curaçao')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (55, 'DK', 'DNK', 'Denmark', 'Dinamarca', 'Danemark')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (56, 'DM', 'DMA', 'Dominica', 'Dominica', 'Dominique')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (57, 'EC', 'ECU', 'Ecuador', 'Ecuador', 'Equateur')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (58, 'EG', 'EGY', 'Egypt', 'Egipto', 'Egypte')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (59, 'SV', 'SLV', 'El Salvador', 'El Salvador', 'El Salvador')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (60, 'AE', 'ARE', 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Emirats Arabes Unis')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (61, 'ER', 'ERI', 'Eritrea', 'Eritrea', 'Erythrée')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (62, 'SK', 'SVK', 'Slovakia', 'Eslovaquia', 'Slovaquie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (63, 'SI', 'SVN', 'Slovenia', 'Eslovenia', 'Slovénie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (64, 'ES', 'ESP', 'Spain', 'España', 'Espagne')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (65, 'US', 'USA', 'United States of America', 'Estados Unidos de América', 'États-Unis d''Amérique')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (66, 'EE', 'EST', 'Estonia', 'Estonia', 'L''Estonie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (67, 'ET', 'ETH', 'Ethiopia', 'Etiopía', 'Ethiopie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (68, 'PH', 'PHL', 'Philippines', 'Filipinas', 'Philippines')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (69, 'FI', 'FIN', 'Finland', 'Finlandia', 'Finlande')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (70, 'FJ', 'FJI', 'Fiji', 'Fiyi', 'Fidji')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (71, 'FR', 'FRA', 'France', 'Francia', 'France')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (72, 'GA', 'GAB', 'Gabon', 'Gabón', 'Gabon')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (73, 'GM', 'GMB', 'Gambia', 'Gambia', 'Gambie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (74, 'GE', 'GEO', 'Georgia', 'Georgia', 'Géorgie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (75, 'GH', 'GHA', 'Ghana', 'Ghana', 'Ghana')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (76, 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Gibraltar')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (77, 'GD', 'GRD', 'Grenada', 'Granada', 'Grenade')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (78, 'GR', 'GRC', 'Greece', 'Grecia', 'Grèce')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (79, 'GL', 'GRL', 'Greenland', 'Groenlandia', 'Groenland')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (80, 'GP', 'GLP', 'Guadeloupe', 'Guadalupe', 'Guadeloupe')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (81, 'GU', 'GUM', 'Guam', 'Guam', 'Guam')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (82, 'GT', 'GTM', 'Guatemala', 'Guatemala', 'Guatemala')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (83, 'GF', 'GUF', 'French Guiana', 'Guayana Francesa', 'Guyane française')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (84, 'GG', 'GGY', 'Guernsey', 'Guernsey', 'Guernesey')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (85, 'GN', 'GIN', 'Guinea', 'Guinea', 'Guinée')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (86, 'GQ', 'GNQ', 'Equatorial Guinea', 'Guinea Ecuatorial', 'Guinée Equatoriale')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (87, 'GW', 'GNB', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinée-Bissau')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (88, 'GY', 'GUY', 'Guyana', 'Guyana', 'Guyane')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (89, 'HT', 'HTI', 'Haiti', 'Haití', 'Haïti')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (90, 'HN', 'HND', 'Honduras', 'Honduras', 'Honduras')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (91, 'HK', 'HKG', 'Hong Kong', 'Hong kong', 'Hong Kong')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (92, 'HU', 'HUN', 'Hungary', 'Hungría', 'Hongrie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (93, 'IN', 'IND', 'India', 'India', 'Inde')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (94, 'ID', 'IDN', 'Indonesia', 'Indonesia', 'Indonésie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (95, 'IR', 'IRN', 'Iran', 'Irán', 'Iran')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (96, 'IQ', 'IRQ', 'Iraq', 'Irak', 'Irak')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (97, 'IE', 'IRL', 'Ireland', 'Irlanda', 'Irlande')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (98, 'BV', 'BVT', 'Bouvet Island', 'Isla Bouvet', 'Bouvet Island')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (99, 'IM', 'IMN', 'Isle of Man', 'Isla de Man', 'Ile de Man')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (100, 'CX', 'CXR', 'Christmas Island', 'Isla de Navidad', 'Christmas Island')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (101, 'NF', 'NFK', 'Norfolk Island', 'Isla Norfolk', 'Île de Norfolk')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (102, 'IS', 'ISL', 'Iceland', 'Islandia', 'Islande')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (103, 'BM', 'BMU', 'Bermuda Islands', 'Islas Bermudas', 'Bermudes')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (104, 'KY', 'CYM', 'Cayman Islands', 'Islas Caimán', 'Iles Caïmans')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (105, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Islas Cocos (Keeling)', 'Cocos (Keeling')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (106, 'CK', 'COK', 'Cook Islands', 'Islas Cook', 'Iles Cook')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (107, 'AX', 'ALA', 'Åland Islands', 'Islas de Åland', 'Îles Åland')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (108, 'FO', 'FRO', 'Faroe Islands', 'Islas Feroe', 'Iles Féro')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (109, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Islas Georgias del Sur y Sandwich del Sur', 'Géorgie du Sud et les Îles Sandwich du Sud')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (110, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Islas Heard y McDonald', 'Les îles Heard et McDonald')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (111, 'MV', 'MDV', 'Maldives', 'Islas Maldivas', 'Maldives')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (112, 'FK', 'FLK', 'Falkland Islands (Malvinas)', 'Islas Malvinas', 'Iles Falkland (Malvinas')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (113, 'MP', 'MNP', 'Northern Mariana Islands', 'Islas Marianas del Norte', 'Iles Mariannes du Nord')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (114, 'MH', 'MHL', 'Marshall Islands', 'Islas Marshall', 'Iles Marshall')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (115, 'PN', 'PCN', 'Pitcairn Islands', 'Islas Pitcairn', 'Iles Pitcairn')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (116, 'SB', 'SLB', 'Solomon Islands', 'Islas Salomón', 'Iles Salomon')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (117, 'TC', 'TCA', 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'Iles Turques et Caïques')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (118, 'UM', 'UMI', 'United States Minor Outlying Islands', 'Islas Ultramarinas Menores de Estados Unidos', 'États-Unis Îles mineures éloignées')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (119, 'VG', 'VGB', 'Virgin Islands', 'Islas Vírgenes Británicas', 'Iles Vierges')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (120, 'VI', 'VIR', 'United States Virgin Islands', 'Islas Vírgenes de los Estados Unidos', 'Îles Vierges américaines')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (121, 'IL', 'ISR', 'Israel', 'Israel', 'Israël')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (122, 'IT', 'ITA', 'Italy', 'Italia', 'Italie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (123, 'JM', 'JAM', 'Jamaica', 'Jamaica', 'Jamaïque')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (124, 'JP', 'JPN', 'Japan', 'Japón', 'Japon')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (125, 'JE', 'JEY', 'Jersey', 'Jersey', 'Maillot')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (126, 'JO', 'JOR', 'Jordan', 'Jordania', 'Jordan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (127, 'KZ', 'KAZ', 'Kazakhstan', 'Kazajistán', 'Le Kazakhstan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (128, 'KE', 'KEN', 'Kenya', 'Kenia', 'Kenya')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (129, 'KG', 'KGZ', 'Kyrgyzstan', 'Kirguistán', 'Kirghizstan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (130, 'KI', 'KIR', 'Kiribati', 'Kiribati', 'Kiribati')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (131, 'KW', 'KWT', 'Kuwait', 'Kuwait', 'Koweït')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (132, 'LB', 'LBN', 'Lebanon', 'Líbano', 'Liban')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (133, 'LA', 'LAO', 'Laos', 'Laos', 'Laos')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (134, 'LS', 'LSO', 'Lesotho', 'Lesoto', 'Lesotho')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (135, 'LV', 'LVA', 'Latvia', 'Letonia', 'La Lettonie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (136, 'LR', 'LBR', 'Liberia', 'Liberia', 'Liberia')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (137, 'LY', 'LBY', 'Libya', 'Libia', 'Libye')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (138, 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (139, 'LT', 'LTU', 'Lithuania', 'Lituania', 'La Lituanie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (140, 'LU', 'LUX', 'Luxembourg', 'Luxemburgo', 'Luxembourg')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (141, 'MX', 'MEX', 'Mexico', 'México', 'Mexique')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (142, 'MC', 'MCO', 'Monaco', 'Mónaco', 'Monaco')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (143, 'MO', 'MAC', 'Macao', 'Macao', 'Macao')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (144, 'MK', 'MKD', 'Macedonia', 'Macedônia', 'Macédoine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (145, 'MG', 'MDG', 'Madagascar', 'Madagascar', 'Madagascar')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (146, 'MY', 'MYS', 'Malaysia', 'Malasia', 'Malaisie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (147, 'MW', 'MWI', 'Malawi', 'Malawi', 'Malawi')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (148, 'ML', 'MLI', 'Mali', 'Mali', 'Mali')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (149, 'MT', 'MLT', 'Malta', 'Malta', 'Malte')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (150, 'MA', 'MAR', 'Morocco', 'Marruecos', 'Maroc')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (151, 'MQ', 'MTQ', 'Martinique', 'Martinica', 'Martinique')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (152, 'MU', 'MUS', 'Mauritius', 'Mauricio', 'Iles Maurice')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (153, 'MR', 'MRT', 'Mauritania', 'Mauritania', 'Mauritanie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (154, 'YT', 'MYT', 'Mayotte', 'Mayotte', 'Mayotte')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (155, 'FM', 'FSM', 'Estados Federados de', 'Micronesia', 'Federados Estados de')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (156, 'MD', 'MDA', 'Moldova', 'Moldavia', 'Moldavie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (157, 'MN', 'MNG', 'Mongolia', 'Mongolia', 'Mongolie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (158, 'ME', 'MNE', 'Montenegro', 'Montenegro', 'Monténégro')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (159, 'MS', 'MSR', 'Montserrat', 'Montserrat', 'Montserrat')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (160, 'MZ', 'MOZ', 'Mozambique', 'Mozambique', 'Mozambique')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (161, 'NA', 'NAM', 'Namibia', 'Namibia', 'Namibie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (162, 'NR', 'NRU', 'Nauru', 'Nauru', 'Nauru')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (163, 'NP', 'NPL', 'Nepal', 'Nepal', 'Népal')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (164, 'NI', 'NIC', 'Nicaragua', 'Nicaragua', 'Nicaragua')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (165, 'NE', 'NER', 'Niger', 'Niger', 'Niger')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (166, 'NG', 'NGA', 'Nigeria', 'Nigeria', 'Nigeria')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (167, 'NU', 'NIU', 'Niue', 'Niue', 'Niou')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (168, 'NO', 'NOR', 'Norway', 'Noruega', 'Norvège')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (169, 'NC', 'NCL', 'New Caledonia', 'Nueva Caledonia', 'Nouvelle-Calédonie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (170, 'NZ', 'NZL', 'New Zealand', 'Nueva Zelanda', 'Nouvelle-Zélande')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (171, 'OM', 'OMN', 'Oman', 'Omán', 'Oman')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (172, 'NL', 'NLD', 'Netherlands', 'Países Bajos', 'Pays-Bas')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (173, 'PK', 'PAK', 'Pakistan', 'Pakistán', 'Pakistan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (174, 'PW', 'PLW', 'Palau', 'Palau', 'Palau')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (175, 'PS', 'PSE', 'Palestine', 'Palestina', 'La Palestine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (176, 'PA', 'PAN', 'Panama', 'Panamá', 'Panama')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (177, 'PG', 'PNG', 'Papua New Guinea', 'Papúa Nueva Guinea', 'Papouasie-Nouvelle-Guinée')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (178, 'PY', 'PRY', 'Paraguay', 'Paraguay', 'Paraguay')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (179, 'PE', 'PER', 'Peru', 'Perú', 'Pérou')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (180, 'PF', 'PYF', 'French Polynesia', 'Polinesia Francesa', 'Polynésie française')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (181, 'PL', 'POL', 'Poland', 'Polonia', 'Pologne')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (182, 'PT', 'PRT', 'Portugal', 'Portugal', 'Portugal')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (183, 'PR', 'PRI', 'Puerto Rico', 'Puerto Rico', 'Porto Rico')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (184, 'QA', 'QAT', 'Qatar', 'Qatar', 'Qatar')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (185, 'GB', 'GBR', 'United Kingdom', 'Reino Unido', 'Royaume-Uni')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (186, 'CF', 'CAF', 'Central African Republic', 'República Centroafricana', 'République Centrafricaine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (187, 'CZ', 'CZE', 'Czech Republic', 'República Checa', 'République Tchèque')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (188, 'DO', 'DOM', 'Dominican Republic', 'República Dominicana', 'République Dominicaine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (189, 'SS', 'SSD', 'South Sudan', 'República de Sudán del Sur', 'Soudan du Sud')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (190, 'RE', 'REU', 'Réunion', 'Reunión', 'Réunion')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (191, 'RW', 'RWA', 'Rwanda', 'Ruanda', 'Rwanda')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (192, 'RO', 'ROU', 'Romania', 'Rumanía', 'Roumanie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (193, 'RU', 'RUS', 'Russia', 'Rusia', 'La Russie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (194, 'EH', 'ESH', 'Western Sahara', 'Sahara Occidental', 'Sahara Occidental')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (195, 'WS', 'WSM', 'Samoa', 'Samoa', 'Samoa')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (196, 'AS', 'ASM', 'American Samoa', 'Samoa Americana', 'Les Samoa américaines')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (197, 'BL', 'BLM', 'Saint Barthélemy', 'San Bartolomé', 'Saint-Barthélemy')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (198, 'KN', 'KNA', 'Saint Kitts and Nevis', 'San Cristóbal y Nieves', 'Saint Kitts et Nevis')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (199, 'SM', 'SMR', 'San Marino', 'San Marino', 'San Marino')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (200, 'MF', 'MAF', 'Saint Martin (French part)', 'San Martín (Francia)', 'Saint-Martin (partie française)')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (201, 'PM', 'SPM', 'Saint Pierre and Miquelon', 'San Pedro y Miquelón', 'Saint-Pierre-et-Miquelon')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (202, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'Saint-Vincent et Grenadines')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (203, 'SH', 'SHN', 'Ascensión y Tristán de Acuña', 'Santa Elena', 'Ascensión y Tristan de Acuña')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (204, 'LC', 'LCA', 'Saint Lucia', 'Santa Lucía', 'Sainte-Lucie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (205, 'ST', 'STP', 'Sao Tome and Principe', 'Santo Tomé y Príncipe', 'Sao Tomé et Principe')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (206, 'SN', 'SEN', 'Senegal', 'Senegal', 'Sénégal')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (207, 'RS', 'SRB', 'Serbia', 'Serbia', 'Serbie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (208, 'SC', 'SYC', 'Seychelles', 'Seychelles', 'Les Seychelles')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (209, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leona', 'Sierra Leone')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (210, 'SG', 'SGP', 'Singapore', 'Singapur', 'Singapour')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (211, 'SX', 'SMX', 'Sint Maarten', 'Sint Maarten', 'Saint-Martin')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (212, 'SY', 'SYR', 'Syria', 'Siria', 'Syrie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (213, 'SO', 'SOM', 'Somalia', 'Somalia', 'Somalie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (214, 'LK', 'LKA', 'Sri Lanka', 'Sri lanka', 'Sri Lanka')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (215, 'ZA', 'ZAF', 'South Africa', 'Sudáfrica', 'Afrique du Sud')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (216, 'SD', 'SDN', 'Sudan', 'Sudán', 'Soudan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (217, 'SE', 'SWE', 'Sweden', 'Suecia', 'Suède')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (218, 'CH', 'CHE', 'Switzerland', 'Suiza', 'Suisse')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (219, 'SR', 'SUR', 'Suriname', 'Surinám', 'Surinam')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (220, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen', 'Svalbard et Jan Mayen')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (221, 'SZ', 'SWZ', 'Swaziland', 'Swazilandia', 'Swaziland')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (222, 'TJ', 'TJK', 'Tajikistan', 'Tayikistán', 'Le Tadjikistan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (223, 'TH', 'THA', 'Thailand', 'Tailandia', 'Thaïlande')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (224, 'TW', 'TWN', 'Taiwan', 'Taiwán', 'Taiwan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (225, 'TZ', 'TZA', 'Tanzania', 'Tanzania', 'Tanzanie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (226, 'IO', 'IOT', 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'Territoire britannique de l''océan Indien')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (227, 'TF', 'ATF', 'French Southern Territories', 'Territorios Australes y Antárticas Franceses', 'Terres australes françaises')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (228, 'TL', 'TLS', 'East Timor', 'Timor Oriental', 'Timor-Oriental')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (229, 'TG', 'TGO', 'Togo', 'Togo', 'Togo')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (230, 'TK', 'TKL', 'Tokelau', 'Tokelau', 'Tokélaou')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (231, 'TO', 'TON', 'Tonga', 'Tonga', 'Tonga')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (232, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinidad y Tobago', 'Trinidad et Tobago')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (233, 'TN', 'TUN', 'Tunisia', 'Tunez', 'Tunisie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (234, 'TM', 'TKM', 'Turkmenistan', 'Turkmenistán', 'Le Turkménistan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (235, 'TR', 'TUR', 'Turkey', 'Turquía', 'Turquie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (236, 'TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Tuvalu')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (237, 'UA', 'UKR', 'Ukraine', 'Ucrania', 'L''Ukraine')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (238, 'UG', 'UGA', 'Uganda', 'Uganda', 'Ouganda')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (239, 'UY', 'URY', 'Uruguay', 'Uruguay', 'Uruguay')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (240, 'UZ', 'UZB', 'Uzbekistan', 'Uzbekistán', 'L''Ouzbékistan')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (241, 'VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Vanuatu')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (242, 'VE', 'VEN', 'Venezuela', 'Venezuela', 'Venezuela')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (243, 'VN', 'VNM', 'Vietnam', 'Vietnam', 'Vietnam')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (244, 'WF', 'WLF', 'Wallis and Futuna', 'Wallis y Futuna', 'Wallis et Futuna')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (245, 'YE', 'YEM', 'Yemen', 'Yemen', 'Yémen')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (246, 'DJ', 'DJI', 'Djibouti', 'Yibuti', 'Djibouti')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (247, 'ZM', 'ZMB', 'Zambia', 'Zambia', 'Zambie')
INSERT INTO public.country(id, iso2, iso3, name_en, name_es, native_name) VALUES (248, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabue', 'Zimbabwe')

ALTER SEQUENCE country_id_seq RESTART WITH 249