export * from './auth.service';
export * from './country.service';
export * from './discipline.service';
export * from './dka.service';
export * from './dkag.service';
export * from './dweight.service';
export * from './institution.service';
export * from './program.service';
export * from './pweight.service';